# Maintainer: Andrey Platonov <poluandrey@gmail.com>

pkgname=consul-template-plugin-system-information
pkgver=${PKGVER:-autogenerated}
pkgrel=${PKGREL:-1}
pkgdesc="Plugin for consul-template which provide system specified values"
arch=('i686' 'x86_64')
license=('MIT')
makedepends=(
	'go'
	'git'
)

source=(
	"git+https://github.com/tears-of-noobs/$pkgname.git#branch=${BRANCH:-master}"
)

md5sums=(
    'SKIP'
)

build() {
	cd "$srcdir/$pkgname"
    make
}

package() {
	cd "$srcdir/$pkgname"

	find .out/ -type f -executable | while read filename; do
		install -DT "$filename" "$pkgdir/usr/bin/$(basename $filename)"
	done
}
